#!/bin/zsh
alias goboot='cd $BOOTSTRAP'
alias gozsh='cd $BOOTSTRAP_ZSH'
alias gobash='cd $BOOTSTRAP_BASH'
alias govim='cd $BOOTSTRAP_NVIM'
alias gotmux='cd $BOOTSTRAP_TMUX'
alias gowork='cd $BOOTSTRAP_WORK'
alias gitkraken='podman compose -f ~/github/gitkraken/compose.yaml up -d 2&>/dev/null'
